/*
 * ProDJEE Arena — question bank.
 *
 * IMPORTANT: every question below is an ORIGINAL SAMPLE written for testing the
 * game engine. None of them is a verified JEE Main / NEET previous-year question.
 * Replace / extend this file with the verified PYQ bank (see README.md for the
 * schema). Fields `year` and `shift` should be filled only from an official source.
 *
 * Schema:
 *   id          unique string
 *   exam        "JEE" | "NEET"
 *   subject     "Physics" | "Chemistry" | "Mathematics" | "Biology"
 *   chapter     chapter name (used for analysis + adaptive rating)
 *   type        "mcq" (single correct, 4 options) | "num" (numerical value)
 *   difficulty  1 (easy) .. 5 (hard)
 *   q           question text (plain text / unicode)
 *   options     [4 items] (mcq only): "text" or { text?, img?, alt? } for image options
 *   img, imgAlt optional figure for the question (path under figures/)
 *   solutionImg optional figure shown with the solution
 *   answer      index 0-3 (mcq) | number (num)
 *   hint        short nudge, shown for 10 s
 *   solution    precise worked solution
 *   source      "Sample (not PYQ)" or e.g. "JEE Main 2023, 29 Jan Shift 1"
 */
window.QBANK = [
  /* ============================ JEE · PHYSICS ============================ */
  { id: "jp01", exam: "JEE", subject: "Physics", chapter: "Kinematics", type: "mcq", difficulty: 1,
    q: "A ball is thrown vertically upward with a speed of 20 m/s. Taking g = 10 m/s², the maximum height reached is:",
    options: ["10 m", "20 m", "40 m", "80 m"], answer: 1,
    hint: "At the top, v = 0. Use v² = u² − 2gh.",
    solution: "0 = u² − 2gh ⇒ h = u²/2g = 400/20 = 20 m." },
  { id: "jp02", exam: "JEE", subject: "Physics", chapter: "Kinematics", type: "num", difficulty: 2,
    q: "A car starts from rest and accelerates uniformly to 30 m/s in 10 s. Find the distance covered (in m) in this time.",
    answer: 150,
    hint: "Area under the v–t graph, or s = ½(u + v)t.",
    solution: "s = ½(u + v)t = ½(0 + 30)(10) = 150 m." },
  { id: "jp03", exam: "JEE", subject: "Physics", chapter: "Laws of Motion", type: "mcq", difficulty: 2,
    q: "Blocks of mass 2 kg and 3 kg are in contact on a smooth floor. A horizontal force of 10 N is applied on the 2 kg block. The contact force between the blocks is:",
    options: ["4 N", "6 N", "10 N", "2 N"], answer: 1,
    hint: "Find the common acceleration first, then look only at the 3 kg block.",
    solution: "a = 10/(2 + 3) = 2 m/s². The contact force alone accelerates the 3 kg block: N = 3 × 2 = 6 N." },
  { id: "jp04", exam: "JEE", subject: "Physics", chapter: "Laws of Motion", type: "mcq", difficulty: 3,
    q: "A block rests on a rough incline. When the angle of the incline is slowly raised to θ, the block just begins to slide. The coefficient of static friction is:",
    options: ["sin θ", "cos θ", "tan θ", "cot θ"], answer: 2,
    hint: "At the verge of sliding, mg sin θ = μ mg cos θ.",
    solution: "Limiting friction: mg sin θ = μ mg cos θ ⇒ μ = tan θ (θ is the angle of repose)." },
  { id: "jp05", exam: "JEE", subject: "Physics", chapter: "Work, Energy & Power", type: "num", difficulty: 1,
    q: "Find the kinetic energy (in J) of a 2 kg body moving at 3 m/s.",
    answer: 9,
    hint: "K = ½mv².",
    solution: "K = ½ × 2 × 3² = 9 J." },
  { id: "jp06", exam: "JEE", subject: "Physics", chapter: "Rotational Motion", type: "mcq", difficulty: 3,
    q: "A uniform solid sphere rolls without slipping. The fraction of its total kinetic energy that is rotational is:",
    options: ["2/7", "2/5", "5/7", "1/2"], answer: 0,
    hint: "I = (2/5)MR² and v = ωR. Compare ½Iω² with ½Mv² + ½Iω².",
    solution: "K_rot = ½(2/5 MR²)(v/R)² = (1/5)Mv². K_total = ½Mv² + (1/5)Mv² = (7/10)Mv². Fraction = (1/5)/(7/10) = 2/7." },
  { id: "jp07", exam: "JEE", subject: "Physics", chapter: "Gravitation", type: "mcq", difficulty: 3,
    q: "The escape speed from Earth is 11.2 km/s. For a planet with the same mean density as Earth but twice its radius, the escape speed is:",
    options: ["11.2 km/s", "15.8 km/s", "22.4 km/s", "44.8 km/s"], answer: 2,
    hint: "Write M in terms of density: M = (4/3)πR³ρ, then v = √(2GM/R).",
    solution: "v = √(2GM/R) = √((8/3)πGρ) · R ⇒ v ∝ R at fixed ρ. Doubling R doubles v: 22.4 km/s." },
  { id: "jp08", exam: "JEE", subject: "Physics", chapter: "Electrostatics", type: "mcq", difficulty: 2,
    q: "Two point charges repel each other with a force F. If each charge is doubled and their separation is also doubled, the new force is:",
    options: ["F/4", "F", "2F", "4F"], answer: 1,
    hint: "F ∝ q₁q₂ / r².",
    solution: "F' ∝ (2q)(2q)/(2r)² = 4q²/4r² = q²/r² ⇒ F' = F." },
  { id: "jp09", exam: "JEE", subject: "Physics", chapter: "Current Electricity", type: "num", difficulty: 1,
    q: "Three resistors of 6 Ω each are connected in parallel. Find the equivalent resistance (in Ω).",
    answer: 2,
    hint: "For n equal resistors in parallel, R_eq = R/n.",
    solution: "1/R = 1/6 + 1/6 + 1/6 = 1/2 ⇒ R = 2 Ω." },
  { id: "jp10", exam: "JEE", subject: "Physics", chapter: "Magnetic Effects of Current", type: "mcq", difficulty: 3,
    q: "The magnetic field at the centre of a circular loop of radius R carrying current I is:",
    options: ["μ₀I / 2πR", "μ₀I / 2R", "μ₀I / 4R", "μ₀IR / 2"], answer: 1,
    hint: "Biot–Savart: every element is perpendicular to its radius vector and at distance R.",
    solution: "dB = μ₀I dl / 4πR². Summing over dl = 2πR: B = μ₀I(2πR)/4πR² = μ₀I/2R." },
  { id: "jp11", exam: "JEE", subject: "Physics", chapter: "Ray Optics", type: "num", difficulty: 3,
    q: "An object is placed 30 cm in front of a convex lens of focal length 20 cm. Find the distance (in cm) of the image from the lens.",
    answer: 60,
    hint: "Lens formula with sign convention: 1/v − 1/u = 1/f, u = −30 cm.",
    solution: "1/v = 1/f + 1/u = 1/20 − 1/30 = 1/60 ⇒ v = +60 cm (real image on the other side)." },
  { id: "jp12", exam: "JEE", subject: "Physics", chapter: "Modern Physics", type: "mcq", difficulty: 2,
    q: "Light of photon energy 5 eV falls on a metal with work function 2 eV. The stopping potential is:",
    options: ["2 V", "3 V", "5 V", "7 V"], answer: 1,
    hint: "Einstein's equation: eV₀ = hν − φ.",
    solution: "eV₀ = 5 eV − 2 eV = 3 eV ⇒ V₀ = 3 V." },
  { id: "jp13", exam: "JEE", subject: "Physics", chapter: "Thermodynamics", type: "mcq", difficulty: 3,
    q: "An ideal gas expands isothermally. The change in its internal energy is:",
    options: ["Equal to heat absorbed", "Zero", "Equal to work done by gas", "Negative"], answer: 1,
    hint: "For an ideal gas, U depends only on temperature.",
    solution: "U = U(T) for an ideal gas. Isothermal ⇒ ΔT = 0 ⇒ ΔU = 0 (so Q = W)." },
  { id: "jp14", exam: "JEE", subject: "Physics", chapter: "Oscillations", type: "mcq", difficulty: 4,
    q: "A spring–mass system has period T. If the mass is made four times, keeping the spring the same, the new period is:",
    options: ["T/2", "T", "2T", "4T"], answer: 2,
    hint: "T = 2π√(m/k).",
    solution: "T ∝ √m. With 4m, T' = √4 · T = 2T." },

  /* =========================== JEE · CHEMISTRY =========================== */
  { id: "jc01", exam: "JEE", subject: "Chemistry", chapter: "Mole Concept", type: "num", difficulty: 1,
    q: "How many moles of water are present in 36 g of H₂O? (Molar mass = 18 g/mol)",
    answer: 2,
    hint: "n = mass / molar mass.",
    solution: "n = 36 / 18 = 2 mol." },
  { id: "jc02", exam: "JEE", subject: "Chemistry", chapter: "Atomic Structure", type: "num", difficulty: 2,
    q: "What is the total number of orbitals in the shell with principal quantum number n = 3?",
    answer: 9,
    hint: "Number of orbitals in shell n is n².",
    solution: "n = 3: one 3s + three 3p + five 3d = 9 = n²." },
  { id: "jc03", exam: "JEE", subject: "Chemistry", chapter: "Chemical Bonding", type: "mcq", difficulty: 3,
    q: "The shape of the XeF₄ molecule is:",
    options: ["Tetrahedral", "Square planar", "See-saw", "Octahedral"], answer: 1,
    hint: "Count bond pairs and lone pairs on Xe: 4 + 2.",
    solution: "Xe has 4 bond pairs + 2 lone pairs (sp³d², octahedral geometry). The lone pairs sit trans to each other ⇒ square planar shape." },
  { id: "jc04", exam: "JEE", subject: "Chemistry", chapter: "Chemical Bonding", type: "mcq", difficulty: 2,
    q: "Which of the following molecules has zero dipole moment?",
    options: ["NH₃", "H₂O", "BF₃", "CHCl₃"], answer: 2,
    hint: "Look for a symmetric shape where bond dipoles cancel.",
    solution: "BF₃ is trigonal planar and symmetric, so the three B–F bond dipoles cancel. The others are polar." },
  { id: "jc05", exam: "JEE", subject: "Chemistry", chapter: "Thermodynamics", type: "mcq", difficulty: 3,
    q: "A reaction is spontaneous at all temperatures when:",
    options: ["ΔH > 0, ΔS > 0", "ΔH < 0, ΔS > 0", "ΔH < 0, ΔS < 0", "ΔH > 0, ΔS < 0"], answer: 1,
    hint: "ΔG = ΔH − TΔS must be negative for every T.",
    solution: "With ΔH < 0 and ΔS > 0, both terms of ΔG = ΔH − TΔS are negative, so ΔG < 0 at every temperature." },
  { id: "jc06", exam: "JEE", subject: "Chemistry", chapter: "Ionic Equilibrium", type: "num", difficulty: 2,
    q: "Find the pH of a 0.001 M HCl solution (assume complete ionisation).",
    answer: 3,
    hint: "pH = −log[H⁺].",
    solution: "[H⁺] = 10⁻³ M ⇒ pH = 3." },
  { id: "jc07", exam: "JEE", subject: "Chemistry", chapter: "Electrochemistry", type: "num", difficulty: 3,
    q: "How many faradays of charge are required to deposit 1 mol of Al from Al³⁺ ions?",
    answer: 3,
    hint: "Al³⁺ + 3e⁻ → Al.",
    solution: "Each Al³⁺ needs 3 electrons, so 1 mol Al needs 3 mol e⁻ = 3 F." },
  { id: "jc08", exam: "JEE", subject: "Chemistry", chapter: "Chemical Kinetics", type: "num", difficulty: 4,
    q: "A first-order reaction has a half-life of 10 min. How long (in min) does it take for 75% completion?",
    answer: 20,
    hint: "75% complete = 25% remaining = two half-lives.",
    solution: "100 → 50 → 25 takes two half-lives = 2 × 10 = 20 min." },
  { id: "jc09", exam: "JEE", subject: "Chemistry", chapter: "Periodic Properties", type: "mcq", difficulty: 3,
    q: "Which of the following has the highest first ionisation enthalpy?",
    options: ["B", "C", "N", "O"], answer: 2,
    hint: "Half-filled p subshells are extra stable.",
    solution: "N (2p³) has a stable half-filled p subshell, so its IE₁ is higher than O's (2p⁴, where removing the paired electron is easier). IE₁: N > O > C > B." },
  { id: "jc10", exam: "JEE", subject: "Chemistry", chapter: "General Organic Chemistry", type: "mcq", difficulty: 2,
    q: "Which carbocation is the most stable?",
    options: ["CH₃⁺", "CH₃CH₂⁺", "(CH₃)₂CH⁺", "(CH₃)₃C⁺"], answer: 3,
    hint: "More alkyl groups ⇒ more hyperconjugation and +I effect.",
    solution: "The tertiary butyl cation has 9 α-hydrogens for hyperconjugation and three +I methyl groups, so it is the most stable." },
  { id: "jc11", exam: "JEE", subject: "Chemistry", chapter: "Alcohols & Carbonyls", type: "mcq", difficulty: 3,
    q: "Which of the following gives a positive iodoform test?",
    options: ["Methanol", "Ethanol", "Propan-1-ol", "Benzaldehyde"], answer: 1,
    hint: "You need a CH₃–CH(OH)– or CH₃–CO– group.",
    solution: "Ethanol is oxidised by I₂/NaOH to CH₃CHO, which has a CH₃CO– unit and gives CHI₃. The others lack this unit." },
  { id: "jc12", exam: "JEE", subject: "Chemistry", chapter: "Coordination Compounds", type: "mcq", difficulty: 2,
    q: "The oxidation state of Fe in K₄[Fe(CN)₆] is:",
    options: ["+2", "+3", "+4", "0"], answer: 0,
    hint: "K is +1 and CN is −1.",
    solution: "4(+1) + x + 6(−1) = 0 ⇒ x = +2." },
  { id: "jc13", exam: "JEE", subject: "Chemistry", chapter: "Solutions", type: "num", difficulty: 3,
    q: "What is the van't Hoff factor (i) of K₂SO₄, assuming complete dissociation?",
    answer: 3,
    hint: "Count the ions produced per formula unit.",
    solution: "K₂SO₄ → 2K⁺ + SO₄²⁻, giving 3 ions ⇒ i = 3." },
  { id: "jc14", exam: "JEE", subject: "Chemistry", chapter: "p-Block Elements", type: "mcq", difficulty: 3,
    q: "Which noble gas forms the largest number of well-characterised compounds?",
    options: ["He", "Ne", "Ar", "Xe"], answer: 3,
    hint: "The lowest ionisation enthalpy among stable noble gases helps.",
    solution: "Xe has a low ionisation enthalpy and a large size, so it forms XeF₂, XeF₄, XeF₆, XeO₃ and others." },

  /* ========================== JEE · MATHEMATICS ========================== */
  { id: "jm01", exam: "JEE", subject: "Mathematics", chapter: "Quadratic Equations", type: "num", difficulty: 2,
    q: "If α and β are the roots of x² − 5x + 6 = 0, find α² + β².",
    answer: 13,
    hint: "α² + β² = (α + β)² − 2αβ.",
    solution: "α + β = 5, αβ = 6 ⇒ α² + β² = 25 − 12 = 13." },
  { id: "jm02", exam: "JEE", subject: "Mathematics", chapter: "Complex Numbers", type: "num", difficulty: 3,
    q: "Find the value of (1 + i)⁸.",
    answer: 16,
    hint: "(1 + i)² = 2i.",
    solution: "(1 + i)⁸ = ((1 + i)²)⁴ = (2i)⁴ = 16 i⁴ = 16." },
  { id: "jm03", exam: "JEE", subject: "Mathematics", chapter: "Sequences & Series", type: "mcq", difficulty: 1,
    q: "The sum of the infinite geometric series 1 + 1/2 + 1/4 + 1/8 + … is:",
    options: ["1", "3/2", "2", "∞"], answer: 2,
    hint: "S∞ = a / (1 − r) for |r| < 1.",
    solution: "a = 1, r = 1/2 ⇒ S∞ = 1/(1 − 1/2) = 2." },
  { id: "jm04", exam: "JEE", subject: "Mathematics", chapter: "Permutations & Combinations", type: "num", difficulty: 3,
    q: "In how many distinct ways can the letters of the word LEVEL be arranged?",
    answer: 30,
    hint: "5 letters with L repeated twice and E repeated twice.",
    solution: "5! / (2! · 2!) = 120 / 4 = 30." },
  { id: "jm05", exam: "JEE", subject: "Mathematics", chapter: "Binomial Theorem", type: "num", difficulty: 2,
    q: "Find the coefficient of x² in the expansion of (1 + x)¹⁰.",
    answer: 45,
    hint: "The general term is ¹⁰Cᵣ xʳ.",
    solution: "¹⁰C₂ = (10 × 9)/2 = 45." },
  { id: "jm06", exam: "JEE", subject: "Mathematics", chapter: "Trigonometry", type: "num", difficulty: 2,
    q: "Find the maximum value of 3 sin x + 4 cos x.",
    answer: 5,
    hint: "The maximum of a sin x + b cos x is √(a² + b²).",
    solution: "√(3² + 4²) = √25 = 5." },
  { id: "jm07", exam: "JEE", subject: "Mathematics", chapter: "Straight Lines", type: "num", difficulty: 3,
    q: "Find the distance between the parallel lines 3x + 4y = 5 and 3x + 4y = 15.",
    answer: 2,
    hint: "d = |c₁ − c₂| / √(a² + b²).",
    solution: "d = |15 − 5| / √(9 + 16) = 10/5 = 2." },
  { id: "jm08", exam: "JEE", subject: "Mathematics", chapter: "Conic Sections", type: "mcq", difficulty: 3,
    q: "The eccentricity of the ellipse x²/25 + y²/9 = 1 is:",
    options: ["3/5", "4/5", "5/4", "3/4"], answer: 1,
    hint: "b² = a²(1 − e²) with a² = 25 and b² = 9.",
    solution: "9 = 25(1 − e²) ⇒ e² = 16/25 ⇒ e = 4/5." },
  { id: "jm09", exam: "JEE", subject: "Mathematics", chapter: "Limits & Continuity", type: "num", difficulty: 2,
    q: "Evaluate lim (x → 0) sin(3x) / x.",
    answer: 3,
    hint: "Multiply and divide by 3 and use lim sin t / t = 1.",
    solution: "sin 3x / x = 3 · (sin 3x / 3x) → 3 · 1 = 3." },
  { id: "jm10", exam: "JEE", subject: "Mathematics", chapter: "Differentiation", type: "num", difficulty: 4,
    q: "If y = xˣ, find dy/dx at x = 1.",
    answer: 1,
    hint: "Take logs: ln y = x ln x.",
    solution: "y'/y = ln x + 1 ⇒ y' = xˣ(1 + ln x). At x = 1: 1 · (1 + 0) = 1." },
  { id: "jm11", exam: "JEE", subject: "Mathematics", chapter: "Definite Integration", type: "mcq", difficulty: 3,
    q: "The value of ∫₀^{π/2} sin²x dx is:",
    options: ["π/2", "π/4", "1", "π"], answer: 1,
    hint: "Use sin²x = (1 − cos 2x)/2, or the King property with cos²x.",
    solution: "I = ∫₀^{π/2} sin²x dx = ∫₀^{π/2} cos²x dx. Adding: 2I = ∫₀^{π/2} 1 dx = π/2 ⇒ I = π/4." },
  { id: "jm12", exam: "JEE", subject: "Mathematics", chapter: "Probability", type: "mcq", difficulty: 2,
    q: "Two fair dice are thrown. The probability that the sum of the numbers is 7 is:",
    options: ["1/6", "5/36", "1/12", "7/36"], answer: 0,
    hint: "List the favourable pairs (1,6), (2,5), …",
    solution: "6 favourable outcomes out of 36 ⇒ 6/36 = 1/6." },
  { id: "jm13", exam: "JEE", subject: "Mathematics", chapter: "Matrices & Determinants", type: "num", difficulty: 4,
    q: "A is a 3 × 3 matrix with |A| = 2. Find |adj A|.",
    answer: 4,
    hint: "|adj A| = |A|ⁿ⁻¹ for an n × n matrix.",
    solution: "|adj A| = 2³⁻¹ = 4." },
  { id: "jm14", exam: "JEE", subject: "Mathematics", chapter: "Vector Algebra", type: "mcq", difficulty: 3,
    q: "a and b are unit vectors inclined at 60°. The value of |a + b| is:",
    options: ["1", "√2", "√3", "2"], answer: 2,
    hint: "|a + b|² = |a|² + |b|² + 2 a·b.",
    solution: "|a + b|² = 1 + 1 + 2 cos 60° = 3 ⇒ |a + b| = √3." },

  /* =========================== NEET · PHYSICS ============================ */
  { id: "np01", exam: "NEET", subject: "Physics", chapter: "Units & Measurements", type: "mcq", difficulty: 1,
    q: "The dimensional formula of force is:",
    options: ["[MLT⁻¹]", "[MLT⁻²]", "[ML²T⁻²]", "[ML⁻¹T⁻²]"], answer: 1,
    hint: "F = ma.",
    solution: "[M][LT⁻²] = [MLT⁻²]." },
  { id: "np02", exam: "NEET", subject: "Physics", chapter: "Kinematics", type: "mcq", difficulty: 1,
    q: "The area under a velocity–time graph gives:",
    options: ["Acceleration", "Displacement", "Speed", "Jerk"], answer: 1,
    hint: "Integrate v with respect to t.",
    solution: "∫v dt = displacement." },
  { id: "np03", exam: "NEET", subject: "Physics", chapter: "Laws of Motion", type: "mcq", difficulty: 1,
    q: "A net force of 20 N acts on a 5 kg body. Its acceleration is:",
    options: ["2 m/s²", "4 m/s²", "25 m/s²", "100 m/s²"], answer: 1,
    hint: "a = F/m.",
    solution: "a = 20/5 = 4 m/s²." },
  { id: "np04", exam: "NEET", subject: "Physics", chapter: "Work, Energy & Power", type: "mcq", difficulty: 2,
    q: "A body is dropped from a height of 5 m (g = 10 m/s²). Its speed just before hitting the ground is:",
    options: ["5 m/s", "10 m/s", "50 m/s", "100 m/s"], answer: 1,
    hint: "mgh = ½mv².",
    solution: "v = √(2gh) = √(2 × 10 × 5) = 10 m/s." },
  { id: "np05", exam: "NEET", subject: "Physics", chapter: "Properties of Fluids", type: "mcq", difficulty: 3,
    q: "The terminal velocity of a small sphere falling through a viscous liquid is proportional to the square of its radius. If the radius is doubled, the terminal velocity becomes:",
    options: ["Half", "Double", "Four times", "Eight times"], answer: 2,
    hint: "v ∝ r².",
    solution: "v ∝ r² ⇒ (2r)² = 4r², so it becomes four times." },
  { id: "np06", exam: "NEET", subject: "Physics", chapter: "Current Electricity", type: "mcq", difficulty: 2,
    q: "The resistance of a bulb rated 100 W, 220 V is:",
    options: ["2.2 Ω", "220 Ω", "484 Ω", "22000 Ω"], answer: 2,
    hint: "P = V²/R.",
    solution: "R = V²/P = 220²/100 = 48400/100 = 484 Ω." },
  { id: "np07", exam: "NEET", subject: "Physics", chapter: "Ray Optics", type: "mcq", difficulty: 3,
    q: "The critical angle for light going from glass of refractive index √2 into air is:",
    options: ["30°", "45°", "60°", "90°"], answer: 1,
    hint: "sin C = 1/n.",
    solution: "sin C = 1/√2 ⇒ C = 45°." },
  { id: "np08", exam: "NEET", subject: "Physics", chapter: "Semiconductors", type: "mcq", difficulty: 2,
    q: "The output of a NAND gate when both inputs are 1 is:",
    options: ["0", "1", "Undefined", "Same as input"], answer: 0,
    hint: "NAND = NOT(AND).",
    solution: "1 AND 1 = 1 ⇒ NOT 1 = 0." },
  { id: "np09", exam: "NEET", subject: "Physics", chapter: "Dual Nature of Matter", type: "mcq", difficulty: 3,
    q: "If the momentum of a particle is doubled, its de Broglie wavelength:",
    options: ["Doubles", "Halves", "Becomes four times", "Remains same"], answer: 1,
    hint: "λ = h/p.",
    solution: "λ ∝ 1/p, so doubling p halves λ." },
  { id: "np10", exam: "NEET", subject: "Physics", chapter: "Thermodynamics", type: "mcq", difficulty: 3,
    q: "The efficiency of a Carnot engine working between 500 K and 300 K is:",
    options: ["20%", "40%", "60%", "67%"], answer: 1,
    hint: "η = 1 − T_cold / T_hot.",
    solution: "η = 1 − 300/500 = 0.4 = 40%." },
  { id: "np11", exam: "NEET", subject: "Physics", chapter: "Waves", type: "mcq", difficulty: 4,
    q: "The fundamental frequency of a pipe of length L closed at one end (speed of sound v) is:",
    options: ["v/2L", "v/4L", "v/L", "2v/L"], answer: 1,
    hint: "The closed end is a node and the open end is an antinode, so L = λ/4.",
    solution: "L = λ/4 ⇒ λ = 4L ⇒ f = v/4L." },
  { id: "np12", exam: "NEET", subject: "Physics", chapter: "Electrostatics", type: "mcq", difficulty: 2,
    q: "The space between the plates of a parallel-plate capacitor is completely filled with a dielectric of constant K. Its capacitance becomes:",
    options: ["C/K", "C", "KC", "K²C"], answer: 2,
    hint: "C = Kε₀A/d.",
    solution: "C' = Kε₀A/d = KC." },

  /* ========================== NEET · CHEMISTRY =========================== */
  { id: "nc01", exam: "NEET", subject: "Chemistry", chapter: "Mole Concept", type: "mcq", difficulty: 1,
    q: "The number of molecules in 1 mole of a substance is approximately:",
    options: ["6.022 × 10²²", "6.022 × 10²³", "3.011 × 10²³", "1.66 × 10⁻²⁴"], answer: 1,
    hint: "Avogadro's number.",
    solution: "N_A ≈ 6.022 × 10²³ per mole." },
  { id: "nc02", exam: "NEET", subject: "Chemistry", chapter: "Periodic Properties", type: "mcq", difficulty: 1,
    q: "The most electronegative element is:",
    options: ["Oxygen", "Chlorine", "Fluorine", "Nitrogen"], answer: 2,
    hint: "Top right of the periodic table (excluding noble gases).",
    solution: "Fluorine has the highest electronegativity (≈ 4.0 on the Pauling scale)." },
  { id: "nc03", exam: "NEET", subject: "Chemistry", chapter: "Chemical Bonding", type: "mcq", difficulty: 2,
    q: "Which of the following molecules is paramagnetic?",
    options: ["N₂", "O₂", "F₂", "CO"], answer: 1,
    hint: "Use MOT and look for unpaired electrons in π* orbitals.",
    solution: "O₂ has two unpaired electrons in the π*2p orbitals, so it is paramagnetic. N₂, F₂ and CO have all electrons paired." },
  { id: "nc04", exam: "NEET", subject: "Chemistry", chapter: "States of Matter", type: "mcq", difficulty: 2,
    q: "At constant temperature, if the pressure of a fixed mass of an ideal gas is doubled, its volume:",
    options: ["Doubles", "Halves", "Stays same", "Becomes four times"], answer: 1,
    hint: "Boyle's law: PV = constant.",
    solution: "P₁V₁ = P₂V₂ ⇒ V₂ = V₁/2." },
  { id: "nc05", exam: "NEET", subject: "Chemistry", chapter: "Chemical Equilibrium", type: "mcq", difficulty: 3,
    q: "For N₂(g) + 3H₂(g) ⇌ 2NH₃(g), ΔH < 0. The yield of NH₃ increases with:",
    options: ["Increase in pressure", "Increase in temperature", "Decrease in pressure", "Adding a catalyst"], answer: 0,
    hint: "Le Chatelier: compare moles of gas on both sides.",
    solution: "4 mol of gas → 2 mol of gas. Higher pressure shifts equilibrium towards fewer moles (forward). Heating favours the backward (endothermic) direction, and a catalyst does not change the yield." },
  { id: "nc06", exam: "NEET", subject: "Chemistry", chapter: "Redox Reactions", type: "mcq", difficulty: 2,
    q: "The oxidation state of Mn in KMnO₄ is:",
    options: ["+4", "+5", "+6", "+7"], answer: 3,
    hint: "K = +1 and O = −2.",
    solution: "+1 + x + 4(−2) = 0 ⇒ x = +7." },
  { id: "nc07", exam: "NEET", subject: "Chemistry", chapter: "Organic Nomenclature", type: "mcq", difficulty: 2,
    q: "The IUPAC name of CH₃–CH(CH₃)–CH₃ is:",
    options: ["Butane", "Isobutane", "2-Methylpropane", "1-Methylpropane"], answer: 2,
    hint: "Longest chain = 3 carbons, with a methyl group on C-2.",
    solution: "Parent chain propane, methyl at C-2 ⇒ 2-methylpropane ('isobutane' is the common name)." },
  { id: "nc08", exam: "NEET", subject: "Chemistry", chapter: "Haloalkanes", type: "mcq", difficulty: 3,
    q: "Which alkyl halide undergoes an S_N1 reaction fastest?",
    options: ["CH₃Br", "CH₃CH₂Br", "(CH₃)₂CHBr", "(CH₃)₃CBr"], answer: 3,
    hint: "S_N1 goes through a carbocation, so its stability decides the rate.",
    solution: "(CH₃)₃CBr gives the most stable (tertiary) carbocation, so it reacts fastest by S_N1." },
  { id: "nc09", exam: "NEET", subject: "Chemistry", chapter: "Biomolecules", type: "mcq", difficulty: 3,
    q: "Which of the following is a non-reducing sugar?",
    options: ["Glucose", "Fructose", "Maltose", "Sucrose"], answer: 3,
    hint: "Check if a free hemiacetal/hemiketal group is present.",
    solution: "In sucrose, the glycosidic bond joins C1 of glucose to C2 of fructose, so both reducing groups are locked. It is non-reducing." },
  { id: "nc10", exam: "NEET", subject: "Chemistry", chapter: "d & f Block Elements", type: "mcq", difficulty: 4,
    q: "Zr and Hf have almost identical atomic radii. This is mainly due to:",
    options: ["Inert pair effect", "Lanthanoid contraction", "Diagonal relationship", "Actinoid contraction"], answer: 1,
    hint: "Think about what comes before Hf in period 6.",
    solution: "The poorly shielding 4f electrons filled before Hf cause lanthanoid contraction, which cancels the expected size increase from Zr to Hf." },
  { id: "nc11", exam: "NEET", subject: "Chemistry", chapter: "Chemical Kinetics", type: "mcq", difficulty: 3,
    q: "The unit of the rate constant for a zero-order reaction is:",
    options: ["s⁻¹", "mol L⁻¹ s⁻¹", "L mol⁻¹ s⁻¹", "L² mol⁻² s⁻¹"], answer: 1,
    hint: "For order n, the unit is (mol L⁻¹)¹⁻ⁿ s⁻¹.",
    solution: "Rate = k[A]⁰ = k, so k has the unit of rate: mol L⁻¹ s⁻¹." },
  { id: "nc12", exam: "NEET", subject: "Chemistry", chapter: "Electrochemistry", type: "mcq", difficulty: 1,
    q: "The standard electrode potential of the standard hydrogen electrode (SHE) is taken as:",
    options: ["+1.00 V", "0.00 V", "−0.76 V", "+0.34 V"], answer: 1,
    hint: "It is the reference electrode.",
    solution: "By convention, E° of SHE = 0.00 V at all temperatures." },

  /* =========================== NEET · BIOLOGY ============================ */
  { id: "nb01", exam: "NEET", subject: "Biology", chapter: "Cell: Structure & Function", type: "mcq", difficulty: 1,
    q: "Which organelle is the main site of aerobic respiration (ATP synthesis) in eukaryotic cells?",
    options: ["Golgi body", "Mitochondrion", "Lysosome", "Ribosome"], answer: 1,
    hint: "It has cristae.",
    solution: "The Krebs cycle (matrix) and oxidative phosphorylation (inner membrane) occur in mitochondria." },
  { id: "nb02", exam: "NEET", subject: "Biology", chapter: "Cell: Structure & Function", type: "mcq", difficulty: 2,
    q: "Ribosomes of prokaryotic cells are of the type:",
    options: ["60S", "70S", "80S", "90S"], answer: 1,
    hint: "Subunits are 50S + 30S.",
    solution: "Prokaryotic ribosomes are 70S (50S + 30S). Eukaryotic cytoplasmic ribosomes are 80S." },
  { id: "nb03", exam: "NEET", subject: "Biology", chapter: "Cell Cycle & Division", type: "mcq", difficulty: 3,
    q: "Crossing over takes place during which stage of meiosis?",
    options: ["Leptotene", "Zygotene", "Pachytene", "Diakinesis"], answer: 2,
    hint: "It comes right after synapsis forms bivalents.",
    solution: "Crossing over (with recombinase) happens between non-sister chromatids during pachytene of prophase I." },
  { id: "nb04", exam: "NEET", subject: "Biology", chapter: "Principles of Inheritance", type: "mcq", difficulty: 2,
    q: "The phenotypic ratio in the F₂ generation of Mendel's dihybrid cross is:",
    options: ["3:1", "1:2:1", "9:3:3:1", "1:1:1:1"], answer: 2,
    hint: "It is two independent 3:1 ratios multiplied.",
    solution: "(3:1) × (3:1) = 9:3:3:1." },
  { id: "nb05", exam: "NEET", subject: "Biology", chapter: "Principles of Inheritance", type: "mcq", difficulty: 3,
    q: "In the AB blood group, both alleles Iᴬ and Iᴮ are expressed. This is an example of:",
    options: ["Incomplete dominance", "Co-dominance", "Epistasis", "Pleiotropy"], answer: 1,
    hint: "Both phenotypes appear fully, with no blending.",
    solution: "Iᴬ and Iᴮ are both fully expressed in the heterozygote, which is co-dominance." },
  { id: "nb06", exam: "NEET", subject: "Biology", chapter: "Molecular Basis of Inheritance", type: "mcq", difficulty: 3,
    q: "Okazaki fragments are formed during DNA replication on the:",
    options: ["Leading strand", "Lagging strand", "Both strands", "Template RNA"], answer: 1,
    hint: "DNA polymerase works only 5′ → 3′.",
    solution: "The lagging strand is synthesised discontinuously (away from the fork) as Okazaki fragments, which DNA ligase later joins." },
  { id: "nb07", exam: "NEET", subject: "Biology", chapter: "Molecular Basis of Inheritance", type: "num", difficulty: 3,
    q: "Out of 64 codons, how many code for amino acids?",
    answer: 61,
    hint: "Subtract the stop codons.",
    solution: "64 − 3 stop codons (UAA, UAG, UGA) = 61 sense codons." },
  { id: "nb08", exam: "NEET", subject: "Biology", chapter: "Photosynthesis", type: "mcq", difficulty: 2,
    q: "The Calvin cycle occurs in the:",
    options: ["Thylakoid lumen", "Stroma", "Grana membrane", "Cytoplasm"], answer: 1,
    hint: "It is the light-independent (dark) reaction.",
    solution: "The Calvin cycle enzymes (including RuBisCO) are in the chloroplast stroma." },
  { id: "nb09", exam: "NEET", subject: "Biology", chapter: "Photosynthesis", type: "mcq", difficulty: 4,
    q: "In C₄ plants, the first stable product of CO₂ fixation is:",
    options: ["3-Phosphoglyceric acid", "Oxaloacetic acid", "Malic acid", "RuBP"], answer: 1,
    hint: "PEP carboxylase fixes CO₂ in mesophyll cells.",
    solution: "PEP + CO₂ → oxaloacetic acid (OAA), a 4-C compound, hence the name 'C₄'." },
  { id: "nb10", exam: "NEET", subject: "Biology", chapter: "Chemical Coordination", type: "mcq", difficulty: 1,
    q: "Which hormone lowers blood glucose level?",
    options: ["Glucagon", "Insulin", "Adrenaline", "Cortisol"], answer: 1,
    hint: "It is secreted by β-cells of the islets of Langerhans.",
    solution: "Insulin increases glucose uptake by cells and glycogenesis, which lowers blood glucose." },
  { id: "nb11", exam: "NEET", subject: "Biology", chapter: "Excretory Products", type: "mcq", difficulty: 1,
    q: "The structural and functional unit of the kidney is:",
    options: ["Neuron", "Nephron", "Alveolus", "Villus"], answer: 1,
    hint: "Each kidney has about a million of them.",
    solution: "The nephron (glomerulus + renal tubule) filters blood and forms urine." },
  { id: "nb12", exam: "NEET", subject: "Biology", chapter: "Ecosystem", type: "mcq", difficulty: 2,
    q: "The 10 per cent law of energy transfer in food chains was given by:",
    options: ["Tansley", "Lindeman", "Odum", "Darwin"], answer: 1,
    hint: "It was proposed in 1942.",
    solution: "Raymond Lindeman proposed that only about 10% of energy passes to the next trophic level." },
  { id: "nb13", exam: "NEET", subject: "Biology", chapter: "Evolution", type: "mcq", difficulty: 3,
    q: "Darwin's finches of the Galápagos Islands are an example of:",
    options: ["Convergent evolution", "Adaptive radiation", "Industrial melanism", "Genetic drift only"], answer: 1,
    hint: "Many forms arose from one ancestral seed-eater.",
    solution: "Different beak types evolved from a common ancestor to fill different niches. This is adaptive radiation." },
  { id: "nb14", exam: "NEET", subject: "Biology", chapter: "Biotechnology", type: "mcq", difficulty: 4,
    q: "The restriction endonuclease EcoRI recognises the palindromic sequence:",
    options: ["5′-GAATTC-3′", "5′-GGATCC-3′", "5′-AAGCTT-3′", "5′-GTTAAC-3′"], answer: 0,
    hint: "It cuts between G and A, leaving AATT sticky ends.",
    solution: "EcoRI: 5′-G↓AATTC-3′. (GGATCC is BamHI, AAGCTT is HindIII, GTTAAC is HpaI.)" },
  { id: "nb15", exam: "NEET", subject: "Biology", chapter: "Human Reproduction", type: "mcq", difficulty: 2,
    q: "Sperms are produced in the:",
    options: ["Vas deferens", "Epididymis", "Seminiferous tubules", "Seminal vesicle"], answer: 2,
    hint: "They are lined by spermatogonia and Sertoli cells.",
    solution: "Spermatogenesis occurs in the seminiferous tubules of the testes. The epididymis only stores the sperms and lets them mature." },
  { id: "nb16", exam: "NEET", subject: "Biology", chapter: "Human Health & Disease", type: "mcq", difficulty: 3,
    q: "The infective stage of Plasmodium injected into humans by a female Anopheles mosquito is the:",
    options: ["Merozoite", "Sporozoite", "Gametocyte", "Trophozoite"], answer: 1,
    hint: "It is stored in the mosquito's salivary glands.",
    solution: "Sporozoites enter the blood with the bite and first multiply in liver cells." },
  { id: "nb17", exam: "NEET", subject: "Biology", chapter: "Plant Kingdom", type: "mcq", difficulty: 2,
    q: "The dominant, independent phase in the life cycle of bryophytes is the:",
    options: ["Sporophyte", "Gametophyte", "Both equally", "Protonema only"], answer: 1,
    hint: "The sporophyte is attached to it and depends on it.",
    solution: "In bryophytes, the haploid gametophyte is dominant and free-living, while the sporophyte is partly dependent on it." },
  { id: "nb18", exam: "NEET", subject: "Biology", chapter: "Digestion & Absorption", type: "mcq", difficulty: 2,
    q: "The largest gland of the human body is the:",
    options: ["Pancreas", "Thyroid", "Liver", "Salivary gland"], answer: 2,
    hint: "It secretes bile.",
    solution: "The liver (about 1.2–1.5 kg in an adult) is the largest gland." },
  /* ================= Figure-based SAMPLES (demonstrate img / image options) ================= */
  { id: "jp15", exam: "JEE", subject: "Physics", chapter: "Current Electricity", type: "num", difficulty: 2,
    q: "Find the equivalent resistance (in Ω) between points A and B in the circuit shown.",
    img: "figures/sample-circuit-01.svg", imgAlt: "A 2 Ω resistor in series with a parallel combination of 3 Ω and 6 Ω, between A and B",
    answer: 4,
    hint: "Reduce the parallel pair first: R = R₁R₂/(R₁ + R₂).",
    solution: "3 Ω ∥ 6 Ω = 18/9 = 2 Ω. In series with 2 Ω: R_AB = 2 + 2 = 4 Ω." },
  { id: "np13", exam: "NEET", subject: "Physics", chapter: "Magnetic Effects of Current", type: "mcq", difficulty: 3,
    q: "A long straight cable of radius R carries a current I distributed uniformly over its cross-section. Which graph correctly shows the magnetic field B versus distance r from the axis?",
    options: [
      { img: "figures/sample-cable-a.svg", alt: "B rises linearly from zero up to r = R, then falls as 1/r" },
      { img: "figures/sample-cable-b.svg", alt: "B constant inside, then falls as 1/r" },
      { img: "figures/sample-cable-c.svg", alt: "B zero inside, jumps at R, then falls as 1/r" },
      { img: "figures/sample-cable-d.svg", alt: "B rises linearly up to R, then stays constant" }
    ], answer: 0,
    hint: "Ampère's law: inside, the enclosed current is I·r²/R².",
    solution: "Inside (r < R): B·2πr = μ₀I r²/R² ⇒ B = μ₀Ir/(2πR²), linear in r. Outside (r ≥ R): B = μ₀I/(2πr), falling as 1/r. Maximum at r = R." },
  /* ============ NEET 2021 · PHYSICS · actual PYQs (from Anu's annotated paper on Drive) ============
   * Only questions whose stem + options were legible AND whose answer matched the paper's key after
   * independent solving. Items with `review` had a detail reconstructed from a noisy scan — verify them. */
  { id: "neet21p02", exam: "NEET", subject: "Physics", chapter: "Electrostatics", type: "mcq", difficulty: 1,
    q: "Polar molecules are the molecules:",
    options: ["having a permanent electric dipole moment.", "having zero dipole moment.", "acquire a dipole moment only in the presence of electric field due to displacement of charges.", "acquire a dipole moment only when magnetic field is absent."], answer: 0,
    hint: "Think of H₂O vs CO₂: what does H₂O have even with no external field?",
    solution: "In polar molecules the centres of positive and negative charge do not coincide, so they have a permanent dipole moment (e.g. H₂O, HCl). Option 3 describes non-polar molecules.",
    source: "NEET 2021 · Physics · Q2" },
  { id: "neet21p06", exam: "NEET", subject: "Physics", chapter: "Magnetic Effects of Current", type: "mcq", difficulty: 2,
    q: "An infinitely long straight conductor carries a current of 5 A. An electron is moving with a speed of 10⁵ m/s parallel to the conductor. The perpendicular distance between the electron and the conductor is 20 cm at an instant. The magnitude of the force experienced by the electron at that instant is:",
    options: ["8 × 10⁻²⁰ N", "4 × 10⁻²⁰ N", "8π × 10⁻²⁰ N", "4π × 10⁻²⁰ N"], answer: 0,
    hint: "B = μ₀I/2πr, then F = evB (v ⊥ B).",
    solution: "B = (2 × 10⁻⁷ × 5)/0.2 = 5 × 10⁻⁶ T. F = evB = 1.6 × 10⁻¹⁹ × 10⁵ × 5 × 10⁻⁶ = 8 × 10⁻²⁰ N.",
    source: "NEET 2021 · Physics · Q6" },
  { id: "neet21p07", exam: "NEET", subject: "Physics", chapter: "Units & Measurements", type: "mcq", difficulty: 2,
    q: "If E and G respectively denote energy and gravitational constant, then E/G has the dimensions of:",
    options: ["[M²][L⁻²][T⁻¹]", "[M²][L⁻¹][T⁰]", "[M][L⁻¹][T⁻¹]", "[M][L⁰][T⁰]"], answer: 1,
    hint: "[G] = [M⁻¹L³T⁻²].",
    solution: "[E]/[G] = [ML²T⁻²]/[M⁻¹L³T⁻²] = [M²L⁻¹T⁰].",
    source: "NEET 2021 · Physics · Q7" },
  { id: "neet21p08", exam: "NEET", subject: "Physics", chapter: "Ray Optics", type: "mcq", difficulty: 1,
    q: "A lens of large focal length and large aperture is best suited as an objective of an astronomical telescope since:",
    options: ["a large aperture contributes to the quality and visibility of the images.", "a large area of the objective ensures better light gathering power.", "a large aperture provides a better resolution.", "all of the above."], answer: 3,
    hint: "Check each statement independently — are any of them false?",
    solution: "Large aperture ⇒ more light gathered (brighter image) and smaller limiting angle ⇒ better resolving power; large focal length ⇒ higher magnification. All statements are true.",
    source: "NEET 2021 · Physics · Q8" },
  { id: "neet21p10", exam: "NEET", subject: "Physics", chapter: "Semiconductors", type: "mcq", difficulty: 2,
    q: "Consider the statements: (A) A zener diode is connected in reverse bias when used as a voltage regulator. (B) The potential barrier of a p-n junction lies between 0.1 V to 0.3 V. Identify the correct answer.",
    options: ["(A) is incorrect but (B) is correct.", "(A) and (B) both are correct.", "(A) and (B) both are incorrect.", "(A) is correct and (B) is incorrect."], answer: 3,
    hint: "Recall the barrier potential of a silicon junction.",
    solution: "(A) True: zener regulates in reverse breakdown. (B) False: barrier is about 0.7 V for Si (≈0.3 V for Ge), not a 0.1–0.3 V range.",
    source: "NEET 2021 · Physics · Q10" },
  { id: "neet21p15", exam: "NEET", subject: "Physics", chapter: "Units & Measurements", type: "mcq", difficulty: 1,
    q: "A screw gauge gives: main scale reading 0 mm, circular scale reading 52 divisions. 1 mm on the main scale corresponds to 100 divisions on the circular scale. The diameter of the wire is:",
    options: ["0.052 cm", "0.52 cm", "0.026 cm", "0.26 cm"], answer: 0,
    hint: "Least count = pitch / number of circular divisions.",
    solution: "LC = 1 mm/100 = 0.01 mm. d = 0 + 52 × 0.01 = 0.52 mm = 0.052 cm.",
    source: "NEET 2021 · Physics · Q15" },
  { id: "neet21p16", exam: "NEET", subject: "Physics", chapter: "Alternating Current", type: "mcq", difficulty: 3,
    q: "An inductor L, a capacitor C and a resistor R are connected in series to an ac source. Potential differences across L, C and R are 40 V, 10 V and 40 V respectively. The amplitude of current in the circuit is 10√2 A. The impedance of the circuit is:",
    options: ["5 Ω", "4√2 Ω", "5/√2 Ω", "4 Ω"], answer: 0,
    hint: "V = √(V_R² + (V_L − V_C)²); use the rms current.",
    solution: "V = √(40² + 30²) = 50 V. I_rms = 10√2/√2 = 10 A. Z = 50/10 = 5 Ω.",
    source: "NEET 2021 · Physics · Q16", review: "V_R value and options read from a noisy scan" },
  { id: "neet21p21", exam: "NEET", subject: "Physics", chapter: "Current Electricity", type: "mcq", difficulty: 1,
    q: "The effective resistance of a parallel connection of four wires of equal length, equal area of cross-section and same material is 0.25 Ω. What will be the effective resistance if they are connected in series?",
    options: ["4 Ω", "0.25 Ω", "0.5 Ω", "1 Ω"], answer: 0,
    hint: "Find the resistance of one wire first.",
    solution: "R/4 = 0.25 ⇒ R = 1 Ω each. In series: 4 × 1 = 4 Ω.",
    source: "NEET 2021 · Physics · Q21" },
  { id: "neet21p22", exam: "NEET", subject: "Physics", chapter: "Nuclei", type: "mcq", difficulty: 2,
    q: "A nucleus with mass number 240 breaks into two fragments each of mass number 120. The binding energy per nucleon of the unfragmented nucleus is 7.6 MeV while that of the fragments is 8.5 MeV. The total gain in binding energy is:",
    options: ["216 MeV", "0.9 MeV", "9.4 MeV", "804 MeV"], answer: 0,
    hint: "Total BE = A × (BE per nucleon). Compare before and after.",
    solution: "Gain = 240 × 8.5 − 240 × 7.6 = 240 × 0.9 = 216 MeV.",
    source: "NEET 2021 · Physics · Q22" },
  { id: "neet21p23", exam: "NEET", subject: "Physics", chapter: "Semiconductors", type: "mcq", difficulty: 2,
    q: "The electron concentration in an n-type semiconductor is the same as the hole concentration in a p-type semiconductor. An external electric field is applied across each of them. Compare the currents in them.",
    options: ["No current will flow in p-type, current will only flow in n-type.", "current in n-type = current in p-type.", "current in p-type > current in n-type.", "current in n-type > current in p-type."], answer: 3,
    hint: "I = neAv_d and v_d = μE. Who is more mobile?",
    solution: "Same carrier concentration, but electron mobility > hole mobility ⇒ larger drift velocity ⇒ I(n-type) > I(p-type).",
    source: "NEET 2021 · Physics · Q23" },
  { id: "neet21p24", exam: "NEET", subject: "Physics", chapter: "Dual Nature of Matter", type: "mcq", difficulty: 2,
    q: "The number of photons per second on an average emitted by a source of monochromatic light of wavelength 600 nm, when it delivers a power of 3.3 × 10⁻³ W, will be: (h = 6.6 × 10⁻³⁴ J s)",
    options: ["10¹⁵", "10¹⁸", "10¹⁷", "10¹⁶"], answer: 3,
    hint: "N = P / (hc/λ).",
    solution: "E = hc/λ = (6.6 × 10⁻³⁴ × 3 × 10⁸)/(6 × 10⁻⁷) = 3.3 × 10⁻¹⁹ J. N = 3.3 × 10⁻³ / 3.3 × 10⁻¹⁹ = 10¹⁶ per second.",
    source: "NEET 2021 · Physics · Q24" },
  { id: "neet21p27", exam: "NEET", subject: "Physics", chapter: "Ray Optics", type: "mcq", difficulty: 2,
    q: "A ray falls normally on one face of a prism (refractive index √3) and meets the second face at an angle of incidence of 30°. Find the angle of emergence from the prism.",
    options: ["90°", "60°", "30°", "45°"], answer: 1,
    hint: "Snell's law at the second face: μ sin 30° = sin e.",
    solution: "√3 × sin 30° = sin e ⇒ sin e = √3/2 ⇒ e = 60°.",
    source: "NEET 2021 · Physics · Q27", review: "original has a figure; described in words here" },
  { id: "neet21p28", exam: "NEET", subject: "Physics", chapter: "Electromagnetic Waves", type: "mcq", difficulty: 2,
    q: "A capacitor of capacitance C is connected across an ac source of voltage V = V₀ sin ωt. The displacement current between the plates of the capacitor would be:",
    options: ["I_d = V₀ωC sin ωt", "I_d = V₀ωC cos ωt", "I_d = (V₀/ωC) sin ωt", "I_d = (V₀/ωC) cos ωt"], answer: 1,
    hint: "I_d = dq/dt with q = CV.",
    solution: "q = CV₀ sin ωt ⇒ I_d = dq/dt = V₀ωC cos ωt (displacement current equals conduction current in the leads).",
    source: "NEET 2021 · Physics · Q28", review: "option 4 partly illegible in scan" },
  { id: "neet21p29", exam: "NEET", subject: "Physics", chapter: "Units & Measurements", type: "mcq", difficulty: 2,
    q: "If force [F], acceleration [A] and time [T] are chosen as fundamental physical quantities, the dimensions of energy are:",
    options: ["[F][A⁻¹][T]", "[F][A][T]", "[F][A][T²]", "[F][A][T⁻¹]"], answer: 2,
    hint: "Energy = force × length. Write length using A and T.",
    solution: "L = A T² (from a = L/T²). E = F × L = [F][A][T²].",
    source: "NEET 2021 · Physics · Q29" },
  { id: "neet21p30", exam: "NEET", subject: "Physics", chapter: "Current Electricity", type: "mcq", difficulty: 1,
    q: "In a potentiometer circuit a cell of EMF 1.5 V gives a balance point at 36 cm length of wire. If another cell of EMF 2.5 V replaces the first cell, at what length of the wire does the balance point occur?",
    options: ["62 cm", "60 cm", "21.6 cm", "64 cm"], answer: 1,
    hint: "E ∝ balancing length.",
    solution: "L = 36 × 2.5/1.5 = 60 cm.",
    source: "NEET 2021 · Physics · Q30" },
  { id: "neet21p31", exam: "NEET", subject: "Physics", chapter: "Oscillations", type: "mcq", difficulty: 1,
    q: "A spring is stretched by 5 cm by a force of 10 N. The time period of oscillations when a mass of 2 kg is suspended by it is:",
    options: ["0.628 s", "0.0628 s", "6.28 s", "3.14 s"], answer: 0,
    hint: "k = F/x, then T = 2π√(m/k).",
    solution: "k = 10/0.05 = 200 N/m. T = 2π√(2/200) = 2π/10 = 0.628 s.",
    source: "NEET 2021 · Physics · Q31" },
  { id: "neet21p35", exam: "NEET", subject: "Physics", chapter: "Work, Energy & Power", type: "mcq", difficulty: 2,
    q: "Water falls from a height of 60 m at the rate of 15 kg/s to operate a turbine. The losses due to frictional force are 10% of the input energy. How much power is generated by the turbine? (g = 10 m/s²)",
    options: ["7.0 kW", "10.2 kW", "8.1 kW", "12.3 kW"], answer: 2,
    hint: "Input power = (dm/dt) g h; output = 90% of it.",
    solution: "P_in = 15 × 10 × 60 = 9000 W. P_out = 0.9 × 9000 = 8100 W = 8.1 kW.",
    source: "NEET 2021 · Physics · Q35" },
  { id: "neet21p36", exam: "NEET", subject: "Physics", chapter: "Electrostatics", type: "mcq", difficulty: 2,
    q: "Twenty seven drops of the same size are charged at 220 V each. They combine to form a bigger drop. The potential of the bigger drop is:",
    options: ["1980 V", "660 V", "1320 V", "1520 V"], answer: 0,
    hint: "Charge adds (27q), radius becomes 27^(1/3) = 3 times.",
    solution: "V' = kQ/R' = k(27q)/(3r) = 9V = 9 × 220 = 1980 V.",
    source: "NEET 2021 · Physics · Q36" },
  { id: "neet21p44", exam: "NEET", subject: "Physics", chapter: "Kinematics", type: "mcq", difficulty: 3,
    q: "A car starts from rest and accelerates at 5 m/s². At t = 4 s, a ball is dropped out of a window by a person sitting in the car. What is the velocity and acceleration of the ball at t = 6 s? (g = 10 m/s²)",
    options: ["20√2 m/s, 10 m/s²", "20 m/s, 5 m/s²", "20 m/s, 0", "20√2 m/s, 0"], answer: 0,
    hint: "Once released, the ball keeps the car's horizontal velocity and only gravity acts.",
    solution: "At release vₓ = 5 × 4 = 20 m/s (stays constant). After 2 s, v_y = 10 × 2 = 20 m/s. v = 20√2 m/s; acceleration = g = 10 m/s².",
    source: "NEET 2021 · Physics · Q44" },
  { id: "neet21p45", exam: "NEET", subject: "Physics", chapter: "Alternating Current", type: "mcq", difficulty: 1,
    q: "A step-down transformer connected to an ac mains supply of 220 V is made to operate an 11 V, 44 W lamp. Ignoring power losses in the transformer, the current in the primary circuit is:",
    options: ["4 A", "0.2 A", "0.4 A", "2 A"], answer: 1,
    hint: "Ideal transformer: input power = output power.",
    solution: "220 × I_p = 44 ⇒ I_p = 0.2 A.",
    source: "NEET 2021 · Physics · Q45" },
  { id: "neet21p46", exam: "NEET", subject: "Physics", chapter: "Laws of Motion", type: "mcq", difficulty: 2,
    q: "A ball of mass 0.15 kg is dropped from a height of 10 m, strikes the ground and rebounds to the same height. The magnitude of impulse imparted to the ball is nearly: (g = 10 m/s²)",
    options: ["1.4 kg m/s", "0 kg m/s", "4.2 kg m/s", "2.1 kg m/s"], answer: 2,
    hint: "Impulse = change in momentum; the velocity reverses.",
    solution: "v = √(2gh) = √200 ≈ 14.1 m/s. J = 2mv = 2 × 0.15 × 14.1 ≈ 4.2 kg m/s.",
    source: "NEET 2021 · Physics · Q46", review: "options 1 and 3 read from a noisy scan" },
  { id: "neet21p47", exam: "NEET", subject: "Physics", chapter: "Alternating Current", type: "mcq", difficulty: 3,
    q: "A series LCR circuit containing a 5.0 H inductor, 80 μF capacitor and 40 Ω resistor is connected to a 230 V variable frequency ac source. The angular frequencies at which power transferred is half the power at resonance are likely to be:",
    options: ["42 rad/s and 58 rad/s", "25 rad/s and 75 rad/s", "50 rad/s and 25 rad/s", "46 rad/s and 54 rad/s"], answer: 3,
    hint: "ω₀ = 1/√(LC); half-power points are ω₀ ± R/2L.",
    solution: "ω₀ = 1/√(5 × 80 × 10⁻⁶) = 50 rad/s. R/2L = 40/10 = 4 rad/s ⇒ 46 and 54 rad/s.",
    source: "NEET 2021 · Physics · Q47" },
  { id: "neet21p50", exam: "NEET", subject: "Physics", chapter: "Magnetic Effects of Current", type: "mcq", difficulty: 3,
    q: "A uniform conducting wire of length 12a and resistance R is wound as a current-carrying coil in the shape of (i) an equilateral triangle of side a, (ii) a square of side a. The magnetic dipole moments of the coil in each case respectively are:",
    options: ["4Ia² and 3Ia²", "√3Ia² and 3Ia²", "3Ia² and Ia²", "3Ia² and 4Ia²"], answer: 1,
    hint: "Number of turns = 12a / perimeter; m = N I A.",
    solution: "Triangle: N = 12a/3a = 4, A = (√3/4)a² ⇒ m = √3 Ia². Square: N = 12a/4a = 3, A = a² ⇒ m = 3Ia².",
    source: "NEET 2021 · Physics · Q50" }
];
