(function(){
'use strict';
var PK='prodjee.student.v1',SK='prodjee.syllabus.v1',AK='prodjee.arena.v1',profile=read(PK,{exam:'',year:2027,targetScore:0}),syllabus=read(SK,{}),arena=read(AK,{}),legacy=read('mtm_state_v1',{}),active=sessionStorage.getItem('prodjee.coach.tab')||'mission',switching=false;
var $=function(s){return document.querySelector(s);},esc=function(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});};
function read(k,f){try{return Object.assign({},f,JSON.parse(localStorage.getItem(k)||'null')||{});}catch(e){return f;}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v));if(window.PJ&&PJ.queueSync)PJ.queueSync();}
function migrate(){if(profile.exam==='JEE'||profile.exam==='NEET')return;var latest=(legacy.mocks||[]).slice().sort(function(a,b){return(+b.createdAt||0)-(+a.createdAt||0);})[0],target=(legacy.profile&&legacy.profile.examTarget)||'';profile.exam=(arena.exam==='JEE'||arena.exam==='NEET')?arena.exam:(latest&&(latest.exam==='NEET'?'NEET':'JEE'))||(/NEET/i.test(target)?'NEET':'JEE');var year=String(target).match(/20\d{2}/);if(year)profile.year=+year[0];save(PK,profile);}
function toast(t){var e=$('#toast');e.textContent=t;e.style.display='block';setTimeout(function(){e.style.display='none';},2200);}
function subjects(){return Object.keys((PJ_SUBJECT_CHAPTERS&&PJ_SUBJECT_CHAPTERS[profile.exam])||{});}
function chapters(){var out=[];subjects().forEach(function(s){PJ_SUBJECT_CHAPTERS[profile.exam][s].forEach(function(c){out.push({subject:s,chapter:c,key:profile.exam+'|'+s+'|'+c});});});return out;}
function stat(k){return(arena.stats&&arena.stats[k])||{att:0,cor:0};}
function weak(){return chapters().map(function(x){var s=stat(x.key);return Object.assign(x,{att:s.att||0,acc:s.att?Math.round(100*s.cor/s.att):null});}).sort(function(a,b){return(a.acc==null?101:a.acc)-(b.acc==null?101:b.acc);})[0];}
function due(){var v=arena.vault||{};return Object.keys(v).filter(function(k){return v[k]&&v[k].due<=Date.now();}).length;}
function mission(){var w=weak(),n=due();return '<section class="card wide"><div class="eyebrow">Today’s mission</div><h2>'+(w&&w.att?'Strengthen '+esc(w.chapter):'Build your baseline')+'</h2><p class="muted">'+(w&&w.att?esc(w.subject)+' · '+w.acc+'% accuracy. Start with adaptive practice, then clear due mistakes.':'Complete a short adaptive run so ProDJEE can identify your weakest chapters.')+'</p><div class="actions"><a class="btn primary" href="/arena/?mission=1&exam='+profile.exam+'">Start 10-question mission</a>'+(n?'<a class="btn ghost" href="/arena/?mode=vault&exam='+profile.exam+'">Revise '+n+' due mistake'+(n===1?'':'s')+'</a>':'')+'</div></section><section class="card wide"><h2>Mistake revision</h2><div class="score">'+n+'</div><div class="muted">due now · questions return after 1, 3 and 7 days</div><div class="actions"><a class="btn '+(n?'primary':'ghost')+'" href="/arena/?mode=vault&exam='+profile.exam+'">Open revision queue</a></div></section>';}
function testBuilder(){return '<section class="card"><h2>Custom test builder</h2><div class="formgrid"><div><label>Subject</label><select id="testSubject">'+subjects().map(function(s){return'<option>'+s+'</option>';}).join('')+'</select></div><div><label>Questions</label><select id="testLength"><option>10</option><option>20</option><option>30</option></select></div><div><label>Chapter</label><select id="testChapter"></select></div><div><label>Difficulty</label><select id="testDifficulty"><option value="any">Adaptive mix</option><option value="easy">Easy · 0–3</option><option value="moderate">Moderate · 4–7</option><option value="difficult">Difficult · 8–10</option></select></div></div><div class="actions"><button class="btn primary" id="startCustom">Build test</button></div></section>';}
function calculator(){return '<section class="card"><h2>Answer-key score calculator</h2><div class="formgrid"><div><label>Correct</label><input id="correct" type="number" min="0" value="0"></div><div><label>Incorrect</label><input id="wrong" type="number" min="0" value="0"></div><div><label>Marks for correct</label><input id="positive" type="number" value="4"></div><div><label>Negative marks</label><input id="negative" type="number" value="1"></div></div><div class="row"><span>Estimated raw score</span><b class="score" id="rawScore">0</b></div><p class="muted">This calculates marks only. It does not claim an official percentile.</p></section>';}
function settings(target){var max=profile.exam==='NEET'?720:300;return '<section class="card wide"><div class="eyebrow">Personalised Coach</div><h2>Coaching goal</h2><label>Target marks out of '+max+'</label><input id="targetScore" type="number" min="1" max="'+max+'" value="'+esc(target)+'" placeholder="Set a target"><div id="targetAdvice" class="muted" style="margin-top:10px"></div><p class="muted settings-note">Your name, age, exam and Google backup remain in Profile. Arena sound, GP goal and reset remain in Arena Rewards.</p></section>';}
function progressSummary(list,ready,target){var sessions=(arena.sessions||[]).filter(function(x){return x.exam===profile.exam;}).slice(-5),correct=sessions.reduce(function(a,x){return a+(x.correct||0);},0),attempted=sessions.reduce(function(a,x){return a+(x.n||0);},0),accuracy=attempted?Math.round(100*correct/attempted):0;return '<section class="card wide"><div class="eyebrow">Progress snapshot</div><h2>'+(target?esc(target)+' marks target':'No score target set yet')+'</h2><div class="progress-metrics"><div><b>'+accuracy+'%</b><span>recent Arena accuracy</span></div><div><b>'+ready+'/'+list.length+'</b><span>chapters test-ready</span></div></div><p class="muted">Targets are changed only in Personalised Coach, so this remains a clear progress view.</p></section>';}
function syllabusCard(list,ready){return '<section class="card wide"><h2>Syllabus & revision dashboard</h2><p class="muted">'+ready+' of '+list.length+' chapters marked test-ready. Update each chapter as your preparation progresses.</p><div class="formgrid"><div><label>Subject</label><select id="syllSubject">'+subjects().map(function(s){return'<option>'+s+'</option>';}).join('')+'</select></div><div><label>Show</label><select id="syllFilter"><option value="all">All chapters</option><option>Not started</option><option>Learning</option><option>Practice</option><option>Revision</option><option>Test ready</option></select></div></div><div class="chapters" id="chapterList"></div></section>';}
function render(){var list=chapters(),ready=list.filter(function(x){return syllabus[x.key]==='Test ready';}).length,target=profile.targetScore||'';$('#examLabel').textContent=profile.exam+' '+profile.year+' · personalised dashboard';document.querySelectorAll('[data-coach-tab]').forEach(function(b){var on=b.dataset.coachTab===active;b.classList.toggle('on',on);b.setAttribute('aria-selected',String(on));});var html=active==='mission'?mission():active==='practice'?testBuilder()+calculator():active==='progress'?progressSummary(list,ready,target)+syllabusCard(list,ready):settings(target);$('#dashboard').innerHTML='<div class="coach-panel">'+html+'</div>';bind();}
function switchTab(next){if(switching||next===active||['mission','practice','progress','settings'].indexOf(next)<0)return;var panel=$('.coach-panel');switching=true;if(panel)panel.classList.add('coach-out');setTimeout(function(){active=next;sessionStorage.setItem('prodjee.coach.tab',next);render();switching=false;},110);}
function fillTest(){var el=$('#testSubject');if(!el)return;var s=el.value;$('#testChapter').innerHTML='<option value="all">All '+s+' chapters</option>'+PJ_SUBJECT_CHAPTERS[profile.exam][s].map(function(c){return'<option value="'+esc(c)+'">'+esc(c)+'</option>';}).join('');}
function fillSyllabus(){var el=$('#syllSubject');if(!el)return;var s=el.value,f=$('#syllFilter').value;$('#chapterList').innerHTML=PJ_SUBJECT_CHAPTERS[profile.exam][s].filter(function(c){return f==='all'||(syllabus[profile.exam+'|'+s+'|'+c]||'Not started')===f;}).map(function(c){var k=profile.exam+'|'+s+'|'+c,v=syllabus[k]||'Not started';return'<div class="chapter"><span>'+esc(c)+'</span><select data-syll="'+esc(k)+'">'+['Not started','Learning','Practice','Revision','Test ready'].map(function(x){return'<option'+(x===v?' selected':'')+'>'+x+'</option>';}).join('')+'</select></div>';}).join('');}
function score(){if(!$('#correct'))return;$('#rawScore').textContent=(+$('#correct').value||0)*(+$('#positive').value||0)-(+$('#wrong').value||0)*(+$('#negative').value||0);}
function advice(){if(!$('#targetScore'))return;var t=+$('#targetScore').value||0;if(!t){$('#targetAdvice').textContent='Set a target to turn progress into a weekly roadmap.';return;}var last=(arena.sessions||[]).filter(function(x){return x.exam===profile.exam;}).slice(-5),acc=last.reduce(function(a,x){return a+(x.correct||0);},0)/Math.max(1,last.reduce(function(a,x){return a+(x.n||0);},0));$('#targetAdvice').textContent=last.length?'Recent Arena accuracy: '+Math.round(acc*100)+'%. Prioritise the daily mission and move weak chapters to Test ready.':'Start with a baseline Arena session; the roadmap will adapt from your accuracy.';}
function bind(){if($('#testSubject')){fillTest();$('#testSubject').onchange=fillTest;$('#startCustom').onclick=function(){location.href='/arena/?mode=chapter&exam='+encodeURIComponent(profile.exam)+'&subject='+encodeURIComponent($('#testSubject').value)+'&chapters='+encodeURIComponent($('#testChapter').value)+'&length='+$('#testLength').value+'&difficulty='+$('#testDifficulty').value;};}if($('#correct')){score();['correct','wrong','positive','negative'].forEach(function(id){$('#'+id).oninput=score;});}if($('#targetScore')){advice();$('#targetScore').onchange=function(){profile.targetScore=+this.value||0;save(PK,profile);advice();toast('Target saved');};}if($('#syllSubject')){fillSyllabus();$('#syllSubject').onchange=fillSyllabus;$('#syllFilter').onchange=fillSyllabus;$('#chapterList').onchange=function(e){if(e.target.dataset.syll){syllabus[e.target.dataset.syll]=e.target.value;save(SK,syllabus);toast('Chapter updated');}};}}
migrate();$('#coachTabs').addEventListener('click',function(e){var b=e.target.closest('[data-coach-tab]');if(b)switchTab(b.dataset.coachTab);});if(window.PJ)PJ.onRemoteData(function(keys){if(keys.some(function(k){return[PK,SK,AK,'mtm_state_v1'].indexOf(k)>=0;}))location.reload();});render();
})();
