(function(){
  'use strict';
  var PROFILE_KEY='prodjee.student.v1', SYLLABUS_KEY='prodjee.syllabus.v1', ARENA_KEY='prodjee.arena.v1';
  var profile=read(PROFILE_KEY,{exam:'',year:2027,targetScore:0});
  var syllabus=read(SYLLABUS_KEY,{}), arena=read(ARENA_KEY,{}), legacyAnalysis=read('mtm_state_v1',{});
  var $=function(s){return document.querySelector(s);}, esc=function(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});};
  function read(k,f){try{return Object.assign(Array.isArray(f)?[]:{},f,JSON.parse(localStorage.getItem(k)||'null')||{});}catch(e){return f;}}
  function save(k,v){localStorage.setItem(k,JSON.stringify(v));if(window.PJ&&PJ.queueSync)PJ.queueSync();}
  function migrateLegacyProfile(){
    if(profile.exam==='JEE'||profile.exam==='NEET')return;
    var latest=(legacyAnalysis.mocks||[]).slice().sort(function(a,b){return (+b.createdAt||0)-(+a.createdAt||0);})[0];
    var target=(legacyAnalysis.profile&&legacyAnalysis.profile.examTarget)||'';
    profile.exam=(arena.exam==='JEE'||arena.exam==='NEET')?arena.exam:(latest&&(latest.exam==='NEET'?'NEET':'JEE'))||(/NEET/i.test(target)?'NEET':'JEE');
    var year=String(target).match(/20\d{2}/);if(year)profile.year=+year[0];
    if(profile.exam)save(PROFILE_KEY,profile);
  }
  function toast(t){var e=$('#toast');e.textContent=t;e.style.display='block';setTimeout(function(){e.style.display='none';},2200);}
  function subjects(){return Object.keys((PJ_SUBJECT_CHAPTERS&&PJ_SUBJECT_CHAPTERS[profile.exam])||{});}
  function allChapters(){var out=[];subjects().forEach(function(s){PJ_SUBJECT_CHAPTERS[profile.exam][s].forEach(function(c){out.push({subject:s,chapter:c,key:profile.exam+'|'+s+'|'+c});});});return out;}
  function statsFor(key){return (arena.stats&&arena.stats[key])||{att:0,cor:0};}
  function weak(){return allChapters().map(function(x){var s=statsFor(x.key);return Object.assign(x,{att:s.att||0,acc:s.att?Math.round(100*s.cor/s.att):null});}).sort(function(a,b){return (a.acc==null?101:a.acc)-(b.acc==null?101:b.acc);})[0];}
  function due(){var bank=arena.vault||{};return Object.keys(bank).filter(function(k){return bank[k]&&bank[k].due<=Date.now();}).length;}
  function render(){
    $('#examLabel').textContent=profile.exam+' '+profile.year+' · personalised dashboard';
    var w=weak(), dueN=due(), target=profile.targetScore||'', chapters=allChapters(), ready=chapters.filter(function(x){return syllabus[x.key]==='Test ready';}).length;
    $('#dashboard').innerHTML=
      '<section class="card wide"><div class="eyebrow">Today’s mission</div><h2>'+(w&&w.att?'Strengthen '+esc(w.chapter):'Build your baseline')+'</h2><p class="muted">'+(w&&w.att?esc(w.subject)+' · '+w.acc+'% accuracy. Start with adaptive practice, then clear due mistakes.':'Complete a short adaptive run so ProDJEE can identify your weakest chapters.')+'</p><div class="actions"><a class="btn primary" href="/arena/?mission=1&exam='+profile.exam+'">Start 10-question mission</a>'+(dueN?'<a class="btn ghost" href="/arena/?mode=vault&exam='+profile.exam+'">Revise '+dueN+' due mistake'+(dueN===1?'':'s')+'</a>':'')+'</div></section>'+ 
      '<section class="card"><h2>Mistake revision</h2><div class="score">'+dueN+'</div><div class="muted">due now · questions return after 1, 3 and 7 days</div><div class="actions"><a class="btn '+(dueN?'primary':'ghost')+'" href="/arena/?mode=vault&exam='+profile.exam+'">Open revision queue</a></div></section>'+ 
      customTest()+scoreCalc()+roadmap(target)+syllabusCard(chapters,ready);
    bind();
  }
  function customTest(){return '<section class="card"><h2>Custom test builder</h2><div class="formgrid"><div><label>Subject</label><select id="testSubject">'+subjects().map(function(s){return '<option>'+s+'</option>';}).join('')+'</select></div><div><label>Questions</label><select id="testLength"><option>10</option><option>20</option><option>30</option></select></div><div><label>Chapter</label><select id="testChapter"></select></div><div><label>Difficulty</label><select id="testDifficulty"><option value="any">Adaptive mix</option><option value="easy">Easy · 0–3</option><option value="moderate">Moderate · 4–7</option><option value="difficult">Difficult · 8–10</option></select></div></div><div class="actions"><button class="btn primary" id="startCustom">Build test</button></div></section>';}
  function scoreCalc(){return '<section class="card"><h2>Answer-key score calculator</h2><div class="formgrid"><div><label>Correct</label><input id="correct" type="number" min="0" value="0"></div><div><label>Incorrect</label><input id="wrong" type="number" min="0" value="0"></div><div><label>Marks for correct</label><input id="positive" type="number" value="4"></div><div><label>Negative marks</label><input id="negative" type="number" value="1"></div></div><div class="row"><span>Estimated raw score</span><b class="score" id="rawScore">0</b></div><p class="muted">This calculates marks only. It does not claim an official percentile.</p></section>';}
  function roadmap(target){var max=profile.exam==='NEET'?720:300;return '<section class="card third"><h2>Score target</h2><label>Target marks out of '+max+'</label><input id="targetScore" type="number" min="1" max="'+max+'" value="'+esc(target)+'" placeholder="Set a target"><div id="targetAdvice" class="muted" style="margin-top:10px"></div></section>';}
  function syllabusCard(chapters,ready){return '<section class="card wide"><h2>Syllabus & revision dashboard</h2><p class="muted">'+ready+' of '+chapters.length+' chapters marked test-ready. Update each chapter as your preparation progresses.</p><div class="formgrid"><div><label>Subject</label><select id="syllSubject">'+subjects().map(function(s){return '<option>'+s+'</option>';}).join('')+'</select></div><div><label>Show</label><select id="syllFilter"><option value="all">All chapters</option><option>Not started</option><option>Learning</option><option>Practice</option><option>Revision</option><option>Test ready</option></select></div></div><div class="chapters" id="chapterList"></div></section>';}
  function fillTestChapters(){var s=$('#testSubject').value;$('#testChapter').innerHTML='<option value="all">All '+s+' chapters</option>'+PJ_SUBJECT_CHAPTERS[profile.exam][s].map(function(c){return '<option value="'+esc(c)+'">'+esc(c)+'</option>';}).join('');}
  function fillSyllabus(){var s=$('#syllSubject').value,f=$('#syllFilter').value;$('#chapterList').innerHTML=PJ_SUBJECT_CHAPTERS[profile.exam][s].filter(function(c){return f==='all'||(syllabus[profile.exam+'|'+s+'|'+c]||'Not started')===f;}).map(function(c){var k=profile.exam+'|'+s+'|'+c,v=syllabus[k]||'Not started';return '<div class="chapter"><span>'+esc(c)+'</span><select data-syll="'+esc(k)+'">'+['Not started','Learning','Practice','Revision','Test ready'].map(function(x){return '<option'+(x===v?' selected':'')+'>'+x+'</option>';}).join('')+'</select></div>';}).join('');}
  function score(){var c=+$('#correct').value||0,w=+$('#wrong').value||0,p=+$('#positive').value||0,n=+$('#negative').value||0;$('#rawScore').textContent=c*p-w*n;}
  function advice(){var t=+$('#targetScore').value||0;if(!t){$('#targetAdvice').textContent='Set a target to turn progress into a weekly roadmap.';return;}var sessions=(arena.sessions||[]).filter(function(x){return x.exam===profile.exam;}),last=sessions.slice(-5),acc=last.reduce(function(a,x){return a+(x.correct||0);},0)/Math.max(1,last.reduce(function(a,x){return a+(x.n||0);},0));$('#targetAdvice').textContent=last.length?'Recent Arena accuracy: '+Math.round(acc*100)+'%. Prioritise the daily mission and move weak chapters to Test ready.':'Start with a baseline Arena session; the roadmap will adapt from your accuracy.';}
  function bind(){fillTestChapters();fillSyllabus();score();advice();$('#testSubject').onchange=fillTestChapters;['correct','wrong','positive','negative'].forEach(function(id){$('#'+id).oninput=score;});$('#targetScore').onchange=function(){profile.targetScore=+this.value||0;save(PROFILE_KEY,profile);advice();toast('Target saved');};$('#syllSubject').onchange=fillSyllabus;$('#syllFilter').onchange=fillSyllabus;$('#chapterList').onchange=function(e){if(e.target.dataset.syll){syllabus[e.target.dataset.syll]=e.target.value;save(SYLLABUS_KEY,syllabus);toast('Chapter updated');}};$('#startCustom').onclick=function(){var s=$('#testSubject').value,c=$('#testChapter').value,n=$('#testLength').value,d=$('#testDifficulty').value;location.href='/arena/?mode=chapter&exam='+encodeURIComponent(profile.exam)+'&subject='+encodeURIComponent(s)+'&chapters='+encodeURIComponent(c)+'&length='+n+'&difficulty='+d;};}
  migrateLegacyProfile();
  if(window.PJ)PJ.onRemoteData(function(keys){if(keys.some(function(k){return [PROFILE_KEY,SYLLABUS_KEY,ARENA_KEY,'mtm_state_v1'].indexOf(k)>=0;}))location.reload();});
  render();
})();
